# permissions for end users to view certificateprofiles.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: certificateprofile-viewer-role
rules:
- apiGroups:
  - yndd.dev
  resources:
  - certificateprofiles
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - yndd.dev
  resources:
  - certificateprofiles/status
  verbs:
  - get
