# permissions for end users to edit certificateprofiles.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: certificateprofile-editor-role
rules:
- apiGroups:
  - yndd.dev
  resources:
  - certificateprofiles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - yndd.dev
  resources:
  - certificateprofiles/status
  verbs:
  - get
