---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - yndd.dev
  resources:
  - certificateprofiles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - yndd.dev
  resources:
  - certificateprofiles/finalizers
  verbs:
  - update
- apiGroups:
  - yndd.dev
  resources:
  - certificateprofiles/status
  verbs:
  - get
  - patch
  - update
